### ISSUE TITLE
Do not run buildAndTest GitHub Action if only markdown changes

### ISSUE THREAD

**Issue by GleasonK** [openxla/stablehlo#110]
### Request description

We should only run build and test if there is a source change, the definition of _source change_ can become more precise over time, but "not markdown" should resolve this issue for the majority of PRs that have come through (spec changes). 

I noticed that #109 triggered a build of the StableHLO source code, when it was a simple markdown fix.

**Comment by GleasonK** [comment]
Can be resolved with adding `paths-ignore` to the action.

```
on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
```
